from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='pharma-index'),
    path('Total_Sales/', views.Sale, name='pharma-sale'),
    path('sales/', views.make_sale, name='pharma-make_sale'),
    path('sales/make_payment/<int:sale_id>/', views.make_payment, name='pharma-make_payment'),
    path('Total/Customers/', views.Total_Customers_view, name='pharma-customer'),
    path('customers/create/', views.create_customer, name='pharma-create_customer'),
    path('customers/update/<int:customer_id>/', views.update_customer, name='pharma-update_customer'),
    path('Drugs_Out_of_Stock/', views.Drugs_Out_of_Stock, name='pharma-drugs_out'),
    path('Total_Profit/', views.Total_Profit, name='pharma-profit'),
    path('Stock/table/', views.stock_table, name='pharma-stock_table'),
    path('Drugs_Added/', views.Drugs_Added, name='pharma-drugs_added'),
    path('Pharmacists/', views.Pharmacist, name='pharma-pharmacist'),
    #path('pharmacists/view/<int:pharmacist_id>/', views.view_pharmacist, name='view-pharmacist'),
    path('Pharmacist_index/', views.pharmacist_index, name='pharma-pharmacist_index'),
    path('medicine/', views.Medicine_view, name='pharma-medicine'),
    path('medicine_list/', views.medicine_list, name='pharma-medicine_list'),
    path('medicines/add/', views.add_medicine, name='pharma-add_medicine'),
    path('edit/medicine/<int:pk>/', views.edit_medicine, name='pharma-edit_medicine'),
    path('delete/medicine/<int:pk>/', views.delete_medicine, name='pharma-delete_medicine'),
    path('calculate_order/', views.calculate_order, name='calculate_order'),
    path('bills/', views.Bill, name='pharma-bill'),
    path('bills/add/', views.add_bill, name='pharma-add_bill'),
    path('bills/<int:bill_id>/', views.bill_detail, name='pharma-bill_detail'),
    path('add-to-cart/<int:medicine_id>/', views.add_to_cart, name='pharma-add_to_cart'),
    path('cart/', views.cart, name='pharma-cart'),
    path('remove-from-cart/<int:cart_item_id>/', views.remove_from_cart, name='pharma-remove_from_cart'),
    path('order', views.order_list, name='pharma-order'),
    path('create/', views.create_order, name='pharma-create_order'),
    path('process-checkout/', views.process_checkout, name='pharma-process-checkout'),
    ]