# Generated by Django 4.2.2 on 2023-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharma", "0002_auto_20230702_1544"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="medicine",),
        migrations.AddField(
            model_name="order",
            name="medicine",
            field=models.ManyToManyField(to="pharma.medicine"),
        ),
    ]
